repos:
  - repo: local
    hooks:
      - id: caddy-fmt
        name: caddy fmt
        entry: bash -c 'docker run --rm -v "$PWD/Caddyfile:/Caddyfile" caddy:2.8 caddy fmt --overwrite /Caddyfile'
        language: system
        files: ^Caddyfile$
