services:
  caddy:
    image: caddy:2.8
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    env_file:
      - .env
    networks:
      - caddy_net

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    volumes:
      - ./kuma-data:/app/data
    networks:
      - caddy_net
    ports:
      - "${TAILSCALE_IP}:3001:3001" # Only accessible on tailnet + via subdomain on Caddyfile
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    external: true
