name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

defaults:
  run:
    working-directory: /home/simlal/vps-homelab

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: |
          echo "Building containers"
          docker compose build

      - name: Deploy infra (caddy + monitoring)
        run: docker compose up -d

      - name: Verify services
        run: docker ps
