name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4
        with:
          path: infra

      - name: Sync repo to persistent infra dir (preserve .env)
        run: |
          rsync -a --delete \
            --exclude '.env' \
            infra/ /home/simlal/infra/

      - name: Deploy infra
        working-directory: /home/simlal/infra
        # HACK: force recreate to avoid unhealthy
        run: docker compose -p infra up -d --force-recreate

      - name: Healthcheck caddy
        working-directory: /home/simlal/infra
        run: docker inspect --format='{{.State.Health.Status}}' caddy
