name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4

      - name: Sync repo into live dir
        run: |
          echo Synching temp runner git checkout @ ref to '~/infra' dir...
          rsync -a --delete ${{ github.workspace }}/ /home/simlal/infra/

      - name: Deploy infra
        run: |
          cd /home/simlal/infra
          docker compose up -d
